### ISSUE TITLE
Update Account from Service

### ISSUE THREAD

**Issue by methinks82** [methinks82/devops-capstone-project#2]
**As a** user
**I need** an account update function  
**So that** I can keep my information up-to-date
      
### Details and Assumptions
    The account number is immutable
    The account name and email are required
    Using REST API

### Acceptance Criteria     
    gherkin 
    Given That a user has an account
    AND the user is logged in to the service with that account
    When the user sends new data to the service using the "POST" method
    Then the information stored in their account will reflect the new information that they submitted

**Comment by manojkumar22092003** [comment]
i will do

**Comment by manojkumar22092003** [comment]
i would like to work on this plz assign
