### ISSUE TITLE
Read an account from service

### ISSUE THREAD

**Issue by methinks82** [methinks82/devops-capstone-project#4]
**As a** user
**I need** a function that retrieves my account information
**So that** I can see my account information
      
### Details and Assumptions
    using REST api
    data returned as json

### Acceptance Criteria     
    gherkin 
    Given A user has an account
    AND the user is logged in with that account
    When they send a request containing their account id
    Then their a json file containing their account info is returned to them

**Comment by hariprasanth05** [comment]
i will take it
